### ISSUE TITLE
xmarks/foxmarks extension login error

### ISSUE THREAD

**Issue by jsamuel** [RequestPolicy/requestpolicy#155]
```
imported trac ticket
created: 2011-01-07 11:23:34
reporter: justin
```

The following discussion thread indicates that there may be a conflict when using xmarks (previously known as foxmarks):

http://getsatisfaction.com/foxmarks/topics/cant_log_in_with_new_version

The addon is Xmarks Sync:

https://addons.mozilla.org/en-US/firefox/addon/2410/

From initial checking, it appears that increasing RP's strictness level above "base domain" causes requests in the login window to be blocked. This can be repeated by increasing strictness, opening the Xmarks window, logging out of Xmarks, clicking the log in button, and when the Xmarks popup login window opens it detects something blocked and assumes it's !NoScript, saying:

  Please whitelist the following Xmarks login server in your !NoScript settings:

  xmarks.com

  And restart your Firefox browser.

The blocked origin/destination pairs all appear to be:

https://login.xmarks.com/ -> https://static.xmarks.com/

**Comment by jsamuel** [comment]
```
imported trac comment
created: 2011-01-07 11:38:28
author: justin
```

Fixed in r385.

**Comment by kaixa** [comment]
thanks
