### ISSUE TITLE
Blocked URL within query data confuses request policy.

### ISSUE THREAD

**Issue by michaeldwells** [RequestPolicy/requestpolicy#285]
I noticed this at www.radiotimes.com, for example:

http://www.radiotimes.com/episode/n8j95/bbc-news--19012012

there are lines such as:

<img src="/rt-service/image/render?imageUrl=http://static.radiotimes.com.edgesuite.net/pa/54/40/webBBCNews10.jpg&amp;width=580&amp;height=327&amp;quality=85" height="327" width="580" alt="BBC News" />

where the image URL contains a blocked URL but is actually loaded from an allowed domain. In this case, I can see the image until the page is fully loaded, when it disappears. May require a slow computer to observe this behaviour.

Using Mozilla Aurora 11.0a2 on Windows 7.

**Comment by ansell** [comment]
What exactly is the issue? If www.radiotimes.com is allowed by requestpolicy the image should be downloaded. The fact that static.radiotimes.com.edgesuite.net is used as a query parameter in the URL is irrelevant to the way requestpolicy works. 

Are you sure this isn't an adblock plus bug? If you want to block that image loading I would suggest setting up an adblock plus rule for it.

**Comment by michaeldwells** [comment]
Hello,

This a late response to let you know it was a clash with the Redirect
Remover plugin. Sorry to have bothered you.

On 19 January 2012 22:59, Peter Ansell <
reply@reply.github.com
