### ISSUE TITLE
Allow multiple policy changes before reload

### ISSUE THREAD

**Issue by Pressfred** [RequestPolicy/requestpolicy#290]
Currently RequestPolicy reloads the page after every single policy change. For some pages this leads to two, three or even more reloads before the page is displayed in a useable way.

Can this be made to work like e.g. NoScript does, where one can make multiple changes before one final reload?

**Comment by jsamuel** [comment]
This is fixed in version 1.0. You can try it out here: https://www.requestpolicy.com/1.0.html
