### ISSUE TITLE
conflict with 1password plug-in

### ISSUE THREAD

**Issue by crun** [RequestPolicy/requestpolicy#298]
spent several days haranguing the agilebits folks because 1password stopped working at upgrade to firefox11. after much back&forth, the guilty party turned out to be a conflict between their plugin and requestpolicy. not sure how to provide you a testcase but this is a high priority issue for me as i need 1password to deal with my faulty memory and requestpolicy to stop all those nasty trackers.

what happens is when requestpolicy is enabled, 1password fails to connect to the 1password helper and thus to the database of passwords. tried to whitelist 127.0.0.1 to no avail.

**Comment by curiousstranger** [comment]
This is affecting me as well.  Please let me know what might be useful in troubleshooting this.

**Comment by crun** [comment]
add the following to your 1password white list "127.0.0.1" and "onepassword-at-agilebits-dot-com" ....

**Comment by curiousstranger** [comment]
To clarify for others reading this, it's the destination whitelist in RequestPolicy (not 1password)

**Comment by crun** [comment]
that's correct. sorry for not being clearer. this whitelist fix solves the conflict for me and thus there's no longer a bug.

**Comment by curiousstranger** [comment]
I'm not sure I'd say there's not a bug.  Having to allow open redirects to 127.0.0.1 is a pretty big hole.  I wonder if there's a way to provide exceptions on a per-addon basis.

**Comment by crun** [comment]
the issue i reported of a conflict with 1password is resolved with that kludge. may i suggest another bug regarding redirects to 127.0.0.1? that way it's clear what the issue is.
