### ISSUE TITLE
about:newtab page in firefox

### ISSUE THREAD

**Issue by shrx** [RequestPolicy/requestpolicy#307]
Firefox has an `about:newtab` page with the top 9 visited sites. I can't access those sites because RequestPolicy denies access from the `about:newtab` page. I can't allow the requests because the flag icon is greyed out and doesn't show any requests.

**Comment by jsamuel** [comment]
Thanks for reporting this. This is now fixed in version 0.5.26b1 which you can try out here: https://www.requestpolicy.com/releases/requestpolicy-BETA.xpi
