### ISSUE TITLE
Request log is broken in 1.x

### ISSUE THREAD

**Issue by aleksejrs** [RequestPolicy/requestpolicy#331]
On Nightly in Esperanto:

Eraro en analizo de XML: nedifinita ento
Looko: chrome://requestpolicy/content/requestLog.xul
Numero de linio 39, Kolumno 7:      <menuitem
------^

**Comment by aleksejrs** [comment]
Same with 16.0b1 en-US.

**Comment by jsamuel** [comment]
Thanks for reporting this. I'll make 1.0.0b2 available today which will include this fix.
