### ISSUE TITLE
Exposing FQDN origin to destination rule options

### ISSUE THREAD

**Issue by KSid** [RequestPolicy/requestpolicy#344]
Users enabling "block by default" and "don't allow requests to the same domain" options in RP 1.x get a UI experience that feels a bit full and clunky. I have been told that only a small percentage of RP users enable that combination of settings so the ideas I've suggested below aim to help keep the base UI as simple as it is now while offering convenient features to those that use more strict default settings.

I have two layout ideas:
- Split the view into two tabs; wildcard and FQDN (or something 
  similar).
- Have a tree view on the left

I prefer the second option because I envision each domain expanding to 
show subdomains when a toggle (or the domain itself) is clicked. That 
way the option is hidden by default for users who don't need the 
functionality and is easily accessible to those who do while still 
presenting the information required without taking too much space. For 
https://roundcubeinbox.wordpress.com/ it might look something  like:

```
roundcubeinbox.wordpress.com <- FQDN instead of 2nd level domain?
|-- wordpress.com
        ^- access rules for a parent domain instead of FQDN,
        ^- maybe put 2nd level domain first
        ^- choosing one changes the origin used in options below

Blocked Destinations
----
flickr.com <- options for (*.)flickr.com
|-- static.flickr.com <- options for (*.)static.flickr.com
    |-- farm7.static.flickr.com <- options for (*.)farm7.static.flickr.com
quantserve.com
|-- pixel.quantserve.com
scorecardresearch.com
|-- sb.scorecardresearch.com
wordpress.com
|-- stats.wordpress.com

Mixed Destinations
----
wp.com <- options for (*.)wp.com
|-- s0.wp.com
|-- s1.wp.com
|-- s2.wp.com
        ^- wp.com is in mixed destinations because
           s2 is allowed but s0 and s1 aren't yet
```

**Comment by Nirkus** [comment]
Hey KSid, im one of those deny-all-by-default guys like you and I'm currently trying the 1.x beta.
It has a lot new features to offer - like a working rule management UI, a really nice in-site UI, a request log...

But it does not allow to control requests on FQ domain names so far. :-/
So, we might want to focus on 1.x and try to get some FQDN-controls in there..

**Comment by KSid** [comment]
Closing this issue as I no longer use RequestPolicy and development has moved to RequestPolicyContinued
