### ISSUE TITLE
Allow icon in navigation bar not just in add-on bar

### ISSUE THREAD

**Issue by wolftune** [RequestPolicy/requestpolicy#397]
I never use the add-on bar, turned it off. It only ever has a couple things and they all are available in the buttons I can put by the navigation bar. RequestPolicy is missing that though, so I can't see the icon.

**Comment by Pawelitel** [comment]
if a pop-up menu in the add-on bar and enter in edit mode, the icon can be transferred in a convenient place of browser interface by drag and drop

**Comment by wolftune** [comment]
You're right, that worked! Unfortunately, it does not work for GNU LibreJS for some reason, so I assumed it wouldn't work, but for RequestPolicy, it did! Thanks for the great tool and the help
