### ISSUE TITLE
Australis (FF29) breaks red/grey flag icon

### ISSUE THREAD

**Issue by wohali** [RequestPolicy/requestpolicy#429]
Even with the add-on bar restored (via Classic Theme Restorer or The Addon Bar) and RequestPolicy moved to the that new toolbar, when RequestPolicy is blocking items on the page, the flag remains grey.

This makes it hard to visually note when RP is actively blocking.

**Comment by wilkowy** [comment]
I think it might be the problem with "addon bar" restored by addons in both cases, as also NoScript has issues (the context menu is in reverse order).

**Comment by profwpollock** [comment]
I have the same issue.  I use statusbar-4-evar and classic theme restorer.

**Comment by bill-hudacek** [comment]
I cannot even get it to show on The Addon Bar.  Customize does not show an icon for RP, and it's nowhere visible on any other toolbar to drag it. So, on a web page I must right-click a blocked element (and it must be _visible_), then I must navigate through context menu, then 2 submenus, to allow each blocked element.  This is an absolute killer and I'll end up disabling or removing it - whether there is some alternative out there or not.  I can't run with it enabled and not be able to whitelist any sites. Ouch. Alas, RP, I knew him well.....

**Comment by profwpollock** [comment]
I got it to show on the status bar (at the bottom; I guess they
call that the add-on bar now) by installing Classic Theme Restorer.
I also have Statusbar-4-evar, but I'm not sure if both are needed.
(My setup is mostly as I want it, and I'm afraid to experiment.)

And still no word on the red/grey icon issue.

## 

Wayne Pollock

**Comment by darnkitten** [comment]
I have this issue as well with ver. 0.5.28 on 29 with classic theme restorer (Ubuntu xfce).  

I did find out that if the button is placed in the default position (nav bar, right side), the red flag works.  Workable, but not ideal, as I place all the rest of of my security buttons on the bottom left, at the base of my tab tree. 

Hopefully, it gets fixed soon.

**Comment by myrdd** [comment]
I was able to fix this bug. Thanks for reporting it! You can get the fixed version (along with other changes) here: https://github.com/RequestPolicyContinued/requestpolicy
Feedback is very welcome.

**Comment by wohali** [comment]
Thanks! Will close this out.
