### ISSUE TITLE
Untrusted connection accessing https://www.requestpolicy.com

### ISSUE THREAD

**Issue by lofidevops** [RequestPolicy/requestpolicy#435]
Steps to reproduce:
- Visit https://www.requestpolicy.com in order to install RP 1.0

What should happen:
- Site available

What happens instead:
- Browser reports invalid security certificate. For example, output from Firefox:
  
  www.requestpolicy.com uses an invalid security certificate. The certificate expired on 10/06/2014 06:46. The current time is 15/06/2014 14:08. (Error code: sec_error_expired_certificate)

**Comment by msliczniak** [comment]
Also not allowed by policy to access the HTTPS URL due to expired cert.
