### ISSUE TITLE
RP 1.0: Icon in Australis menu is invisible

### ISSUE THREAD

**Issue by lofidevops** [RequestPolicy/requestpolicy#436]
Steps to reproduce:
- Install RP 1.0 in Firefox 30
- In Firefox, open menu and select Customize
- In Customize panel, drag RP icon (flag) from toolbar to menu (the Australis menu)
- Click "Exit Customize"
- In Firefox, open menu

What should happen:
- RP icon no longer appears in toolbar
- RP icon appears in menu
- RP functionality accessible from menu instead of toolbar

What happens instead:
- RP icon no longer appears in toolbar (correct)
- RP text appears in menu, but icon is not visible, dropdown arrow appears next to invisible icon
- RP functionality is accessible as expected (correct)

**Comment by myrdd** [comment]
thanks for your report. I've implemented support for the flag in the new firefox menu, see https://github.com/RequestPolicyContinued/requestpolicy.

**Comment by lofidevops** [comment]
Thanks! Do we need to build the XPI ourselves at the moment?

**Comment by myrdd** [comment]
yes, but I'm working on setting up a simple web page with an update-url for the addon ("nightly" updates).

**Comment by lofidevops** [comment]
That's great. I'll watch the https://github.com/RequestPolicyContinued/requestpolicy repo for news.

**Comment by myrdd** [comment]
Great! You can download the xpi here: https://sslsites.de/requestpolicy.256k.de/ I'm looking forward to your feedback!

**Comment by lofidevops** [comment]
(I'm assuming feedback should continue on this ticket, otherwise happy to move discussion to a ticket in the Continued repo.)

Running 1.0.0b5 this issue is partially resolved. After starting Firefox, the RP icon is still not visible in the menu. Eventually, though, it becomes visible in the appropriate color.

I'm not 100% sure, but it looks like when it's in the toolbar (and always visible), it starts as "dark grey" ("no status" perhaps?) and then switches to the correct color at some point (which may include "light grey"). The different shades may be a figment of my imagination though.

**Comment by myrdd** [comment]
I can't reproduce what you're saying. First, there are no different grey colors, [just one](https://github.com/RequestPolicyContinued/requestpolicy/blob/dev-1.0/src/skin/requestpolicy-icon-allowed.png).

Which menu exactly do you mean? The _requestpolicy menu_ is the menu that pops up when you click on the flag. Well, that might be clear, but then there's the _Tools_ menu in the old _Menu Bar_ and the new _australis_ menu which was introduced by Firefox 29.

So, please give some more details and maybe screenshots. When I click on the _australis_ menu, then on _Customize_, the RP flag switches to red and is movable. See screenshot.

![bug-436-1](https://cloud.githubusercontent.com/assets/4286829/3910135/185be9f2-2315-11e4-9941-79ba524d52af.jpg)

Btw, yes, it's good to post the posts here, as they're created already. New issues, if not reported already, you could post on the Continued repo.

**Comment by lofidevops** [comment]
Ah, I guess I kind of expanded the scope of what I originally reported :) If you move the flag to the Australis menu, now does remain visible. However, when you restart Firefox, the icon is not visible for a while. (I'm using Firefox 31.0 on Ubuntu 14.04)

**Comment by myrdd** [comment]
Oh I see, I have the same issue. The flag appears as soon as you visit a website.

**Comment by lofidevops** [comment]
To test this I set my homepage to a public URL (it's normally blank), quit Firefox, started Firefox and waited for page to load completely (no more "loading" messages at the bottom). When I opened the Australis menu, the flag was unfortunately not visible (see screenshot).

I assume that there is some logic is involved in choosing to show the grey or red flag. Perhaps it could show the grey flag by default? Or some other color that indicates "still working" (blue)?

As the original poster, I should note that given that it does eventually load, this is now a low priority issue (for me). Many thanks for the fixes so far!

![no-request-policy-logo](https://cloud.githubusercontent.com/assets/229415/4029213/d071ca2c-2c4b-11e4-852b-49931565df6d.png)

**Comment by myrdd** [comment]
I was curious, so I fixed this ;) Would be great if you could test it!
https://github.com/RequestPolicyContinued/requestpolicy/commit/e52275f86740486b45a2bcbc197a90b833ee4fec

edit: there's only one case which is not solved: if your homepage is `about:blank`, you'll get a red icon instead of a gray one on the firefox start.

**Comment by lofidevops** [comment]
@myrdd Thanks! Is an XPI available? I'm not sure I'll have time to test from source. If not yet available, I'm happy to wait and test with next beta release.

**Comment by myrdd** [comment]
wow, fast answer. no xpi available. ok, you can wait for the next beta release.

**Comment by lofidevops** [comment]
Confirmed working with 1.0.0b7 (XPI from GitHub releases page).
