### ISSUE TITLE
Not available for Firefox 36.0

### ISSUE THREAD

**Issue by rgaiacs** [RequestPolicy/requestpolicy#449]

**Comment by myrdd** [comment]
thank you @r-gaia-cs for reporting this! I've created an issue in the "Continued" Project, see https://github.com/RequestPolicyContinued/requestpolicy/issues/525 – please continue discussion there.

We have to work on a compatible release. Currently I'm working on 1.0, but it's still beta (and still will be some time), so a compatibility release is necessary.
