### ISSUE TITLE
Has issues with IPv6

### ISSUE THREAD

**Issue by tokudan** [RequestPolicy/requestpolicy#458]
Accessing a site over it's IPv6 address has problems:
http://[2a03:2267:0:0:1111:1111:1111:1111]/
results in Requestpolicy denying access to the "domain" 2a03:2267:0:0:1111:1111:1111:1111.

**Comment by myrdd** [comment]
Hi @tokudan, in case you're using RP 1.0 beta, could you please report again [there](https://github.com/RequestPolicyContinued/requestpolicy/issues) with steps how to reproduce?
