### ISSUE TITLE
Using back button in a newly opened tab

### ISSUE THREAD

**Issue by Watilin** [RequestPolicy/requestpolicy#462]
When I use a middle-click to open a link in a new tab, and this link’s domain is normally blocked by RequestPolicy, then navigate to another page in this new tab, I find myself unable to use the Back button to go back to the previous page.

Example:
1. Navigate to http://typematrix.com/2030/why.php
2. Make sure that requests from _typematrix.com_ to _wikipedia.org_ are not allowed
3. Middle-click the link “Repetitive Strain Injury” to open it in a new tab
4. In this new tab, click any link to navigate away from the current page
5. Hit the Back button.

Nothing happens when I click the back button. Thereafter, if I allow requests from _typematrix.com_ to _wikipedia.com_, the button gets working again.

**Comment by myrdd** [comment]
Hi, version 0.5.x is not maintained anymore. This issue is fixed in the 1.0.beta branch. However, this that branch still has some major problems, see this link:
https://github.com/RequestPolicyContinued/requestpolicy/issues?q=is%3Aopen+is%3Aissue+label%3A%221.0+vs+0.5%22

**Comment by Watilin** [comment]
Oh right, I forgot about that. Thanks for reminding it to me.
