### ISSUE TITLE
Middle click and open in new tab messed up

### ISSUE THREAD

**Issue by ghost** [RequestPolicy/requestpolicy#465]
Middle clicking a link or right clicking and selecting "open in new tab" produces a weird behavior recently:
- if the destination domain would be permitted by request policy for the current site, the new tab opens properly
- if there is no such whitelisting (i.e. if the current site would do a request for the destination link's domain, it would get rejected by request policy) then the following happens: 
  - a popup appears on the current page from request policy advising me that the page is trying to redirect (to the destination page)
  - a new tab opens that doesn't load but has the destination url filled into the url bar.

Using the CTRL+left click on a link doesn't seem to be influenced by these things at all.

Obviously, the second case should not happen, even if the current page wouldn't be able to request something from that domain, it should be allowed to open a new tab on that domain.

I attached a screenshot of how it looks: I am on reddit.com and middle clicked on a link leading to imgur.com. RP is configured with reject all and there is no whitelist from reddit.com to imgur.com. If I add a whitelist or select "temporarily allow all requests" the bug doesn't happen any more.

Let me know if you need any other information and thank you for a great plugin!

Kind regards,
Voicu

![rp_bug](https://cloud.githubusercontent.com/assets/3177305/11014816/2eb7d04c-854f-11e5-90d3-4efd153db6a1.png)

**Comment by myrdd** [comment]
Hi Voicu, please add the version of RP you're using. If you're using [RPC](https://requestpolicycontinued.github.io/), please report the problem [there](https://github.com/RequestPolicyContinued/requestpolicy/issues). I think those middle-click issues should be fixed in the latest RPC versions.

**Comment by ghost** [comment]
Hello,

You're right, I downloaded RPC beta and it's fixed. It also looks great :)

Thank you again for a great addon.

Regards,

Voicu
